Repository djud17-org/todoList, pull requests merged in 2023-04, with the labels that each got.

#59 TD-23 Поправлена верстка TaskListScene с помощью PinLayout
  taskManager/Helpers/Constants.swift
  taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
  taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskTableViewCell.swift
Labels: enhancement

#60 LoginVC layout redesigned with PinLayout
  taskManager/Helpers/Constants.swift
  taskManager/Scenes/Login/LoginViewController.swift
Labels: enhancement

#68 Feature/td 27.1/add color theme
  taskManager.xcodeproj/project.pbxproj
  taskManager/Default/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon~ios-marketing.png
  taskManager/Default/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  taskManager/Helpers/Constants.swift
  taskManager/Helpers/Extensions/UIColor+Hex.swift
  taskManager/Helpers/Theme.swift
  taskManager/Scenes/Login/LoginViewController.swift
  taskManager/Scenes/TaskList/TaskListViewController.swift
  taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
  taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskTableViewCell.swift
  taskManagerTests/UIColorHexTests.swift
Labels: bug, enhancement

#70 TD-26 Настроен swiftgen, поправлены локализации
  taskManager.xcodeproj/project.pbxproj
  taskManager/Scenes/Login/LoginPresenter.swift
  taskManager/Scenes/Login/LoginRouter.swift
  taskManager/Scenes/Login/LoginViewController.swift
  taskManager/Scenes/Login/LoginWorker.swift
  taskManager/Scenes/TaskList/TaskListViewController.swift
  taskManager/Supporting files/AppDelegate.swift
  taskManager/Supporting files/Base.lproj/LaunchScreen.storyboard
  taskManager/Supporting files/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  taskManager/Supporting files/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon~ios-marketing.png
  taskManager/Supporting files/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  taskManager/Supporting files/Resources/Assets.xcassets/Contents.json
  taskManager/Supporting files/Resources/Autogenerated/Assets.swift
  taskManager/Supporting files/Resources/Autogenerated/Strings.swift
  taskManager/Supporting files/Resources/en.lproj/Localizable.strings
  taskManager/Supporting files/Resources/ru.lproj/Localizable.strings
  taskManager/Supporting files/SceneDelegate.swift
  taskManager/Supporting files/ru.lproj/LaunchScreen.strings
  taskManager/SwiftGen/Templates/Assets.stencil
  taskManager/SwiftGen/Templates/Strings.stencil
  taskManager/SwiftGen/swiftgen.sh
  taskManager/SwiftGen/swiftgen.yml
Labels: enhancement

#78 TD-32 Созданы UI тесты для LoginScene
  taskManager.xcodeproj/project.pbxproj
  taskManager.xcodeproj/xcshareddata/xcschemes/taskManager.xcscheme
  taskManager/Helpers/Extensions/Date.swift
  taskManagerTests/LoginScene/LoginScreenObject.swift
  taskManagerUITests/LoginScreen/LoginScreenObject.swift
  taskManagerUITests/LoginScreen/LoginUITests.swift
  taskManagerUITests/UI-Common/BaseScreenObject.swift
  taskManagerUITests/UI-Common/Predicates.swift
Labels: enhancement

#79 TD-31
  taskManager.xcodeproj/project.pbxproj
  taskManager/Helpers/Extensions/String+Localized.swift
  taskManager/Helpers/Extensions/UITableView.swift
  taskManager/Helpers/Protocols/ICellAccessibility.swift
  taskManager/Helpers/Protocols/ICellViewModel.swift
  taskManager/Scenes/TaskList/Auxhiliary/TaskListSceneAccessibilityIdentifier.swift
  taskManager/Scenes/TaskList/TaskListViewController.swift
  taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskCellModel.swift
  taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
  taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskCellModel.swift
  taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskTableViewCell.swift
  taskManager/Services/SectionManager.swift
  taskManagerUITests/TaskList/TaskListScreenObject.swift
Labels: enhancement

#81 TD-33 Написать UI-тесты для TodoListScene
  taskManager.xcodeproj/project.pbxproj
  taskManagerUITests/LoginScreen/LoginScreenObject.swift
  taskManagerUITests/LoginScreen/LoginUITests.swift
  taskManagerUITests/TaskList/TaskListScreenObject.swift
  taskManagerUITests/TaskList/TaskListUITests.swift
Labels: enhancement

#86 update readme
  .obsidian/workspace.json
  README.md
Labels: documentation
