Repository djud17-org/todoList, pull requests merged in 2023-03, with the labels that each got.

#9 feat(TD-4): Add task models tests
  taskManager.xcodeproj/project.pbxproj
  taskManager.xcodeproj/xcshareddata/xcschemes/taskManager.xcscheme
  taskManager.xcodeproj/xcuserdata/antonzaricnyj.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  taskManager.xcodeproj/xcuserdata/antonzaricnyj.xcuserdatad/xcschemes/xcschememanagement.plist
  taskModelsTests/ImportantTaskModelTests.swift
  taskModelsTests/RegularTaskModelTests.swift
  taskModelsTests/TaskModelTests.swift
Labels: enhancement

#21 TD-9 Тесты для SectionManager
  TaskManagerTests/Services/SectionManagerTests.swift
  taskManager.xcodeproj/project.pbxproj
Labels: enhancement

#23 Feature/td 6/task manager package
  TaskManagerPackage/.gitignore
  TaskManagerPackage/.swiftpm/xcode/package.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TaskManagerPackage/Package.swift
  TaskManagerPackage/README.md
  TaskManagerPackage/Sources/TaskManagerPackage/ImportantTask.swift
  TaskManagerPackage/Sources/TaskManagerPackage/OrderedTaskManager.swift
  TaskManagerPackage/Sources/TaskManagerPackage/RegularTask.swift
  TaskManagerPackage/Sources/TaskManagerPackage/Task.swift
  TaskManagerPackage/Sources/TaskManagerPackage/TaskManager.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/ImportantTaskModelTests.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/OrderedTaskManagerTests.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/RegularTaskModelTests.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/TaskManagerTests.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/TaskModelTests.swift
  TaskManagerTests/Services/SectionManagerTests.swift
  taskManager.xcodeproj/project.pbxproj
  taskManager/Scenes/TaskList/TaskListAssembly.swift
  taskManager/Scenes/TaskList/TaskListModel.swift
  taskManager/Scenes/TaskList/TaskListPresenter.swift
  taskManager/Scenes/TaskList/View/Cell/ImportantTask/ImportantTaskTableViewCell.swift
  taskManager/Scenes/TaskList/View/Cell/RegularTask/RegularTaskTableViewCell.swift
  taskManager/Services/SectionManager.swift
  taskManager/Services/TaskRepository.swift
Labels: enhancement

#26 Add worker tests
  taskManager.xcodeproj/project.pbxproj
  taskManagerTests/LoginScene/WorkerTests.swift
Labels: enhancement

#35 TD-13
  TaskManagerPackage/Tests/TaskManagerPackageTests/ImportantTaskModelTests.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/ImportantTaskTests.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/RegularTaskModelTests.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/RegularTaskTests.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/TaskModelTests.swift
  TaskManagerPackage/Tests/TaskManagerPackageTests/TaskTests.swift
Labels: bug

#36 fix(TD-11): Исправлена настройка линтера
  taskManager.xcodeproj/project.pbxproj
Labels: bug

#44 TD-17 Тесты для интерактора - toDoList
  taskManager.xcodeproj/project.pbxproj
  taskManager/Scenes/Login/LoginAssembly.swift
  taskManager/Scenes/Login/LoginInteractor.swift
  taskManager/Scenes/Login/LoginWorker.swift
  taskManagerTests/LoginScene/LoginInteractor/LoginInteractorTests.swift
  taskManagerTests/LoginScene/LoginInteractor/LoginPresenterSpy.swift
  taskManagerTests/LoginScene/LoginInteractor/LoginWorkerSpy.swift
Labels: enhancement

#43 Feature/TD-16/Тесты для LoginScene
  TaskManagerPackage/.swiftpm/xcode/xcshareddata/xcschemes/TaskManagerPackage.xcscheme
  taskManager.xcodeproj/project.pbxproj
  taskManager/Scenes/Login/LoginAssembly.swift
  taskManager/Scenes/Login/LoginInteractor.swift
  taskManager/Scenes/Login/LoginPresenter.swift
  taskManager/Scenes/Login/LoginViewController.swift
  taskManager/Scenes/Login/LoginWorker.swift
  taskManagerTests/LoginScene/LoginInteractorTest.swift
  taskManagerTests/LoginScene/LoginPresenterTests.swift
  taskManagerTests/LoginScene/LoginViewControllerTests.swift
  taskManagerTests/LoginScene/Test Doubles/LoginInteractorSpy.swift
  taskManagerTests/LoginScene/Test Doubles/LoginPresenterSpy.swift
  taskManagerTests/LoginScene/Test Doubles/LoginViewControllerSpy.swift
  taskManagerTests/LoginScene/Test Doubles/LoginWorkerSpy.swift
Labels: enhancement

#49 Добавлены тесты для интерактора - модуль taskList
  taskManager.xcodeproj/project.pbxproj
  taskManager/Scenes/TaskList/TaskLisInteractor.swift
  taskManager/Scenes/TaskList/TaskListAssembly.swift
  taskManagerTests/TaskListScene/TaskInteractor/SectionManagerSpy.swift
  taskManagerTests/TaskListScene/TaskInteractor/TaskListInteractorTests.swift
  taskManagerTests/TaskListScene/TaskInteractor/TaskListPresenterSpy.swift
  taskManagerTests/TaskListScene/TaskListInteractor/SectionManagerSpy.swift
  taskManagerTests/TaskListScene/TaskListInteractor/TaskListInteractorTests.swift
  taskManagerTests/TaskListScene/TaskListInteractor/TaskListPresenterSpy.swift
Labels: enhancement

#52 ReadMe update
  README.md
Labels: documentation

#47 feat(TD-19): Добавлены тесты для TaskListViewController
  taskManager.xcodeproj/project.pbxproj
  taskManager/Scenes/Login/LoginWorker.swift
  taskManagerTests/TaskListScene/TaskListInteractorTests.swift
  taskManagerTests/TaskListScene/TaskListViewControllerTests.swift
  taskManagerTests/TaskListScene/TaskPresenterTests.swift
  taskManagerTests/TaskListScene/Test Doubles/SectionManagerSpy.swift
  taskManagerTests/TaskListScene/Test Doubles/TaskListInteractorSpy.swift
  taskManagerTests/TaskListScene/Test Doubles/TaskListPresenterSpy.swift
  taskManagerTests/TaskListScene/Test Doubles/TaskListViewControllerSpy.swift
Labels: enhancement
